/* ═══════════════════════════════════════════════════════════════
   TASKBOOST.AI — INTERNATIONALISATION (i18n)
   Languages: English (en) · Spanish (es) · German (de)
═══════════════════════════════════════════════════════════════ */

const translations = {

  /* ─────────────────────────────────────────────────────────────
     ENGLISH (default)
  ───────────────────────────────────────────────────────────── */
  en: {
    // NAV
    nav_solutions: "Solutions",
    nav_industries: "Industries",
    nav_how: "How It Works",
    nav_about: "About",
    nav_reviews: "Reviews",
    nav_contact: "Contact",
    nav_cta: "Book Consultation",
    rev_label: "Client Reviews",
    rev_title: "What our clients say",
    rev_sub: "Real results from real businesses. Every review is verified and approved before it appears here.",
    rev_form_h: "Worked with us? Leave a review",
    rev_form_sub: "Your review will be sent to our team for approval before going live.",
    rev_pick_stars: "Select your rating",
    rev_name: "Your Name *",
    rev_company: "Company (optional)",
    rev_role: "Your Role (optional)",
    rev_text: "Your Review *",
    rev_submit: "Submit Review",
    rev_note: "Reviewed by our team before publishing · Your email is never shared",
    rev_success: "Thank you! We'll review your submission and publish it soon.",

    // HERO
    hero_badge: "AI Automation",
    hero_title1: "Automate Workflows.",
    hero_title2: "Scale Smarter.",
    hero_ethics: "AI Ethics is our core value — we build automation that is transparent, fair, and human-first.",
    hero_subtitle: "Taskboost.ai builds practical AI automation systems that help e-commerce and real estate companies eliminate manual work, streamline operations, and improve customer interactions.",
    hero_cta1: "Get Your Free AI Automation Audit",
    hero_cta2: "See How It Works",
    hero_trust1: "AWS Solutions Architect Certified",
    card1_label: "Lead Qualification",
    card1_value: "247 leads processed",
    card2_label: "AI Support Response",
    card2_value: "Response in &lt; 2 seconds",
    card3_label: "Manual Tasks Saved",
    card3_value: "~80% reduction",

    // VALUE
    val_label: "Why AI Automation",
    val_title: "Your business shouldn't run on manual work",
    val_sub: "Most companies lose hundreds of hours every month to repetitive tasks. Taskboost.ai replaces that with AI systems that work 24/7.",
    val1_h: "Eliminate Manual Work",
    val1_p: "Stop paying your team to copy-paste data, send follow-up emails, or qualify leads by hand. AI handles the repetitive work automatically.",
    val2_h: "Instant Customer Response",
    val2_p: "AI assistants respond to customers in seconds — 24/7, in multiple languages — without adding headcount or increasing your support costs.",
    val3_h: "Automate Operations End-to-End",
    val3_p: "From lead capture to CRM entry to contract processing — we build connected AI pipelines that replace entire manual workflows.",
    val4_h: "Scale Without Hiring",
    val4_p: "Grow your volume of leads, orders, or property inquiries without growing your team proportionally. AI scales with you.",

    // INDUSTRIES
    ind_label: "Industries We Serve",
    ind_title: "Built for e-commerce.<br />Built for real estate.",
    ind_sub: "Deep focus on two industries where AI automation delivers the highest impact.",
    ind1_tag: "Automation for online stores & marketplaces",
    ind1_li1: "AI customer support assistant",
    ind1_li2: "Product recommendation assistant",
    ind1_li3: "Order automation workflows",
    ind1_li4: "CRM & marketing automation",
    ind1_li5: "AI product question assistant",
    ind1_li6: "Returns & refund workflow automation",
    ind1_btn: "Explore E-commerce Solutions",
    ind2_tag: "Automation for agencies & property teams",
    ind2_li1: "AI lead qualification system",
    ind2_li2: "Property inquiry assistant",
    ind2_li3: "Appointment scheduling automation",
    ind2_li4: "CRM integration & automation",
    ind2_li5: "Multilingual communication automation",
    ind2_li6: "Document processing for contracts",
    ind2_btn: "Explore Real Estate Solutions",
    flex_h: "Don't see your industry listed?",
    flex_p: "Even if we haven't worked in your niche yet, our AI automation frameworks can adapt to almost any business workflow. We analyze your processes, identify automation opportunities, and build AI systems tailored to your operations.",
    flex_btn: "Let's Talk",

    // SHOWCASE
    show_label: "Real Impact",
    show_title: "AI automation in action",
    show_sub: "From e-commerce stores to real estate agencies — teams that automate scale faster, respond quicker, and close more deals.",
    show1_tag: "E-Commerce",
    show1_h: "Customer support automated.<br />Team finally focuses on growth.",
    show1_p: "AI answers product questions, processes returns, and qualifies buyers — without a single human touchpoint.",
    show2_tag: "Real Estate",
    show2_h: "Every lead qualified automatically.",
    show2_p: "AI chats with new inquiries, books viewings, and updates the CRM — so agents only talk to serious buyers.",
    show3_tag: "Operations",
    show3_h: "80% less manual work. Same team.",
    show3_p: "Automated workflows replace repetitive tasks so your team spends time on what actually moves the business forward.",
    stat1_label: "Reduction in manual tasks",
    stat2_label: "AI customer response time",
    stat3_label: "Automated operations",
    stat4_label: "From audit to live automation",

    // SOLUTIONS
    sol_label: "AI Solutions",
    sol_title: "What we build for you",
    sol_sub: "Practical AI automation systems designed for real business workflows — not just demos.",
    sol1_h: "AI Lead Qualification",
    sol1_p: "Automatically score, qualify, and route leads 24/7. Never let a hot lead wait while your team is offline.",
    sol1_tag: "Sales Automation",
    sol2_h: "AI Customer Support Assistant",
    sol2_p: "Deploy AI that answers customer questions instantly, escalates when needed, and learns from your knowledge base.",
    sol2_tag: "Customer Experience",
    sol3_h: "AI Sales Follow-Up Automation",
    sol3_p: "Automated follow-up sequences triggered by behavior, stage, or time — personalized by AI, sent at the right moment.",
    sol3_tag: "Sales Automation",
    sol4_h: "AI Appointment Scheduling",
    sol4_p: "Let AI handle booking, rescheduling, and reminders automatically. Integrates with your calendar and CRM.",
    sol4_tag: "Operations",
    sol5_h: "AI CRM & Workflow Automation",
    sol5_p: "Automate data entry, pipeline updates, and task creation inside your CRM. Keep your team focused on closing deals.",
    sol5_tag: "Operations",
    sol6_h: "AI Document Processing",
    sol6_p: "Extract, classify, and process data from contracts, forms, and invoices automatically — no manual entry required.",
    sol6_tag: "Document AI",
    sol7_h: "AI Knowledge Assistant",
    sol7_p: "Deploy an internal AI assistant trained on your company knowledge — for your team or your customers.",
    sol7_tag: "Knowledge AI",
    sol8_h: "AI-Powered Website Development",
    sol8_p: "We design and build fast, modern websites for your business — optimized for conversions, mobile-first, and ready to connect with your AI automation stack from day one.",
    sol8_tag: "Web Development",
    sol9_h: "Visibility on Google & AI Search",
    sol9_p: "We optimize your online presence so your business gets found — on Google, and inside AI assistants like ChatGPT, Claude, Gemini, and Perplexity. The future of search is AI-driven.",
    sol9_tag: "AI Search & SEO",
    sol_cta_h: "Not sure which solution fits?",
    sol_cta_p: "We start every engagement with a free AI Automation Audit to identify the highest-impact opportunities in your specific workflow.",
    sol_cta_btn: "Get Your Free Audit",

    // HOW IT WORKS
    how_label: "The Process",
    how_title: "From audit to live automation<br />in weeks, not months.",
    how_sub: "A clear, structured process that delivers results fast.",
    step1_h: "Free AI Audit",
    step1_p: "We analyze your current workflows, identify bottlenecks, and map out exactly where AI automation will deliver the most value — at no cost.",
    step2_h: "Identify Opportunities",
    step2_p: "We prioritize automation opportunities by ROI, build a clear roadmap, and align on the systems that make the most impact for your business.",
    step3_h: "Build & Implement",
    step3_p: "We build the AI workflows using n8n, OpenAI, Claude AI, and modern APIs — tested, integrated, and connected to your existing tools.",
    step4_h: "Launch & Optimize",
    step4_p: "We deploy your automation systems, monitor performance, and continuously optimize so they improve over time.",
    how_cta: "Start with a Free AI Audit",

    // WHY
    why_label: "Why Taskboost.ai",
    why_title: "Practical AI.<br />Real results.",
    why_desc: "We don't sell AI hype. We build automation systems that work inside your real business processes, using modern tools, and deliver measurable impact.",
    why_btn: "Book a Free Consultation",
    why1_h: "Practical Implementation First",
    why1_p: "We focus on automation that runs in your real environment — not proofs of concept that never reach production.",
    why2_h: "Modern AI Stack",
    why2_p: "We use n8n, OpenAI, Claude AI, AWS AI services, and modern APIs — the same tools powering the world's best automation teams.",
    why3_h: "Founder-Led Expertise",
    why3_p: "You work directly with the founders. No account managers, no junior handoffs — just experienced engineers who understand your business.",
    why4_h: "Multilingual Capabilities",
    why4_p: "We work with clients and build AI systems in English, German, Spanish, Portuguese, Romanian, and Catalan.",
    why5_h: "AWS Solutions Architect Certified",
    why5_p: "Our team holds AWS Solutions Architect certification — ensuring enterprise-grade architecture decisions for every project.",
    why6_h: "Focused on Real Results",
    why6_p: "We measure success by time saved, leads qualified, costs reduced — not by the complexity of the technology we use.",

    // TOOLS
    tools_label: "Our Tech Stack",
    tools_title: "Built with the best AI tools available",
    tools_sub: "We use the most powerful and reliable AI and automation tools to build systems that work — and keep working.",
    tool1_role: "Workflow Automation Engine",
    tool1_desc: "Open-source automation platform that connects all your apps, triggers, and AI agents into powerful end-to-end workflows.",
    tool1_badge: "Core Platform",
    tool2_role: "GPT-4o · Embeddings · Assistants API",
    tool2_desc: "Powers our conversational AI, lead qualification, product assistants, and intelligent document processing workflows.",
    tool2_badge: "AI Models",
    tool3_role: "Anthropic · Claude 3.5 Sonnet & Opus",
    tool3_desc: "Used for complex reasoning, long-context document analysis, knowledge assistants, and nuanced customer interactions.",
    tool3_badge: "AI Models",
    tool4_role: "Textract · Comprehend · Lambda · S3",
    tool4_desc: "Enterprise-grade cloud infrastructure and AI services for document processing, data storage, and scalable automation pipelines.",
    tool4_badge: "AWS Certified",
    tool5_role: "Custom Integrations · Real-time Triggers",
    tool5_desc: "We connect any tool that has an API — CRMs, e-commerce platforms, calendars, databases, and communication channels.",
    tool5_badge: "Integration",
    tool6_role: "Pinecone · Supabase · Embeddings",
    tool6_desc: "Knowledge retrieval systems that let your AI assistants answer questions from your own data, documents, and product catalog.",
    tool6_badge: "Knowledge AI",

    // FOUNDERS
    found_label: "The Team",
    found_sub: "Taskboost.ai was founded in March 2026 in Berlin, Germany, by an engineer and a philosopher with a shared belief: AI automation should be practical, fast to deploy, and built on ethical foundations that create real value for people and businesses.",
    found1_role: "Co-Founder & Tech Lead",
    found1_bio: "Technology specialist with 10+ years of experience at big tech companies and startups across cloud infrastructure and software development. Brings deep engineering expertise in AI systems, automation architecture, and modern API integrations to every project.",
    found1_li: "Connect on LinkedIn",
    found2_role: "Co-Founder & AI Ethics · Philosophy & IT",
    found2_bio: "Philosopher with an IT background who ensures every system we build is grounded in ethical principles. Brings a rare combination of technical knowledge and philosophical rigor — shaping how Taskboost.ai thinks about AI responsibility, transparency, and long-term impact.",
    ethics_h: "Our commitment to ethical AI",
    ethics_p: "We believe AI automation should empower people — not replace their judgment, compromise their privacy, or create systems they don't understand. Every automation we build is designed to be transparent, fair, and genuinely useful. Philosophy isn't a side interest here — it shapes how we think about every system we build.",
    berlin_badge: "Founded March 2026 · Berlin, Germany",

    // CONTACT
    contact_label: "Get in Touch",
    contact_title: "Start with a<br />Free AI Audit.",
    contact_desc: "Tell us about your business and we'll identify the most impactful AI automation opportunities — completely free, no commitment.",
    contact_email_label: "Email",
    contact_wa_label: "WhatsApp",
    contact_loc_label: "Location",
    contact_loc_val: "Berlin, Germany",
    contact_loc_sub: "We work with clients worldwide",
    contact_lang_label: "We speak",
    form_name: "Full Name *",
    form_email: "Business Email *",
    form_company: "Company",
    form_phone: "Phone / WhatsApp",
    form_industry: "Industry",
    form_country: "Country",
    form_other_industry: "Your Industry",
    form_message: "Tell us about your workflow *",
    ph_name: "Your full name",
    ph_email: "you@company.com",
    ph_company: "Company name",
    ph_phone: "+1 234 567 8900",
    ph_country: "Your country",
    ph_other_industry: "e.g. Healthcare, Logistics, Finance...",
    ph_message: "Describe the manual processes you'd like to automate, or the challenges you're facing...",
    opt_select: "Select industry",
    opt_ecomm: "E-Commerce",
    opt_re: "Real Estate",
    opt_other: "Other",
    form_submit: "Get Your Free AI Audit",
    form_success_msg: "<strong>Message sent!</strong><p>We'll review your workflow and get back to you within 24 hours.</p>",

    // FOOTER
    footer_tagline: "Practical AI automation for e-commerce and real estate companies. Built in Berlin, serving clients globally.",
    footer_sol: "Solutions",
    footer_sol1: "AI Lead Qualification",
    footer_sol2: "AI Customer Support",
    footer_sol3: "Sales Follow-Up Automation",
    footer_sol4: "Appointment Scheduling",
    footer_sol5: "CRM Automation",
    footer_sol6: "Document Processing",
    footer_ind: "Industries",
    footer_ind1: "E-Commerce",
    footer_ind2: "Real Estate",
    footer_ind3: "Other Industries",
    footer_company: "Company",
    footer_comp1: "About",
    footer_comp2: "Founders",
    footer_comp3: "How It Works",
    footer_comp4: "Contact",
    footer_contact: "Contact",
    footer_copy: "&copy; 2026 Taskboost.ai · All rights reserved · Berlin, Germany",
  },

  /* ─────────────────────────────────────────────────────────────
     SPANISH (es)
  ───────────────────────────────────────────────────────────── */
  es: {
    // NAV
    nav_solutions: "Soluciones",
    nav_industries: "Sectores",
    nav_how: "Cómo Funciona",
    nav_about: "Nosotros",
    nav_reviews: "Reseñas",
    nav_contact: "Contacto",
    nav_cta: "Reservar Consulta",
    rev_label: "Reseñas de Clientes",
    rev_title: "Lo que dicen nuestros clientes",
    rev_sub: "Resultados reales de empresas reales. Cada reseña es verificada y aprobada antes de publicarse.",
    rev_form_h: "¿Trabajaste con nosotros? Deja tu reseña",
    rev_form_sub: "Tu reseña será enviada a nuestro equipo para aprobación antes de publicarse.",
    rev_pick_stars: "Seleccioná tu calificación",
    rev_name: "Tu Nombre *",
    rev_company: "Empresa (opcional)",
    rev_role: "Tu Cargo (opcional)",
    rev_text: "Tu Reseña *",
    rev_submit: "Enviar Reseña",
    rev_note: "Revisada por nuestro equipo antes de publicar · Tu email no se comparte",
    rev_success: "¡Gracias! Revisaremos tu reseña y la publicaremos pronto.",

    // HERO
    hero_badge: "Automatización con IA",
    hero_title1: "Automatiza tus Procesos.",
    hero_title2: "Escala con Inteligencia.",
    hero_ethics: "La ética en IA es nuestro valor fundamental — construimos automatización transparente, justa y centrada en las personas.",
    hero_subtitle: "Taskboost.ai construye sistemas prácticos de automatización con IA que ayudan a empresas de e-commerce e inmobiliarias a eliminar el trabajo manual, optimizar operaciones y mejorar la experiencia del cliente.",
    hero_cta1: "Obtén tu Auditoría de IA Gratuita",
    hero_cta2: "Ver Cómo Funciona",
    hero_trust1: "Certificado AWS Solutions Architect",
    card1_label: "Calificación de Leads",
    card1_value: "247 leads procesados",
    card2_label: "Respuesta de Soporte IA",
    card2_value: "Respuesta en &lt; 2 segundos",
    card3_label: "Tareas Manuales Ahorradas",
    card3_value: "~80% de reducción",

    // VALUE
    val_label: "Por Qué Automatizar con IA",
    val_title: "Tu negocio no debería depender del trabajo manual",
    val_sub: "La mayoría de las empresas pierden cientos de horas al mes en tareas repetitivas. Taskboost.ai las reemplaza con sistemas de IA que trabajan las 24 horas, los 7 días de la semana.",
    val1_h: "Elimina el Trabajo Manual",
    val1_p: "Deja de pagar a tu equipo para copiar datos, enviar correos de seguimiento o calificar leads a mano. La IA se encarga del trabajo repetitivo de forma automática.",
    val2_h: "Respuesta Instantánea al Cliente",
    val2_p: "Los asistentes de IA responden a los clientes en segundos — 24/7, en múltiples idiomas — sin aumentar tu equipo ni tus costes de soporte.",
    val3_h: "Automatiza las Operaciones de Extremo a Extremo",
    val3_p: "Desde la captación de leads hasta la entrada en el CRM y el procesamiento de contratos — construimos pipelines de IA conectados que reemplazan flujos de trabajo manuales completos.",
    val4_h: "Escala sin Contratar",
    val4_p: "Aumenta tu volumen de leads, pedidos o consultas inmobiliarias sin hacer crecer tu equipo de forma proporcional. La IA escala contigo.",

    // INDUSTRIES
    ind_label: "Sectores en los que Trabajamos",
    ind_title: "Diseñado para e-commerce.<br />Diseñado para inmobiliarias.",
    ind_sub: "Especialización profunda en dos sectores donde la automatización con IA genera el mayor impacto.",
    ind1_tag: "Automatización para tiendas online y marketplaces",
    ind1_li1: "Asistente de atención al cliente con IA",
    ind1_li2: "Asistente de recomendación de productos",
    ind1_li3: "Flujos de trabajo para gestión de pedidos",
    ind1_li4: "Automatización de CRM y marketing",
    ind1_li5: "Asistente de consultas sobre productos",
    ind1_li6: "Automatización de devoluciones y reembolsos",
    ind1_btn: "Explorar Soluciones para E-commerce",
    ind2_tag: "Automatización para agencias y equipos inmobiliarios",
    ind2_li1: "Sistema de calificación de leads con IA",
    ind2_li2: "Asistente de consultas sobre propiedades",
    ind2_li3: "Automatización de programación de visitas",
    ind2_li4: "Integración y automatización de CRM",
    ind2_li5: "Automatización de comunicación multilingüe",
    ind2_li6: "Procesamiento de documentos y contratos",
    ind2_btn: "Explorar Soluciones Inmobiliarias",
    flex_h: "¿No ves tu sector en la lista?",
    flex_p: "Aunque no hayamos trabajado en tu nicho todavía, nuestros frameworks de automatización con IA se adaptan a casi cualquier flujo de trabajo empresarial. Analizamos tus procesos, identificamos oportunidades de automatización y construimos sistemas de IA a medida para tus operaciones.",
    flex_btn: "Hablemos",

    // SHOWCASE
    show_label: "Impacto Real",
    show_title: "La automatización con IA en acción",
    show_sub: "Desde tiendas de e-commerce hasta agencias inmobiliarias — los equipos que automatizan escalan más rápido, responden antes y cierran más operaciones.",
    show1_tag: "E-Commerce",
    show1_h: "Soporte al cliente automatizado.<br />El equipo se centra en crecer.",
    show1_p: "La IA responde preguntas sobre productos, gestiona devoluciones y califica compradores — sin ninguna intervención humana.",
    show2_tag: "Inmobiliaria",
    show2_h: "Cada lead calificado automáticamente.",
    show2_p: "La IA gestiona nuevas consultas, agenda visitas y actualiza el CRM — para que los agentes solo hablen con compradores serios.",
    show3_tag: "Operaciones",
    show3_h: "80% menos trabajo manual. El mismo equipo.",
    show3_p: "Los flujos automatizados reemplazan las tareas repetitivas para que tu equipo invierta su tiempo en lo que realmente impulsa el negocio.",
    stat1_label: "Reducción de tareas manuales",
    stat2_label: "Tiempo de respuesta de la IA al cliente",
    stat3_label: "Operaciones automatizadas",
    stat4_label: "De la auditoría a la automatización en vivo",

    // SOLUTIONS
    sol_label: "Soluciones de IA",
    sol_title: "Lo que construimos para ti",
    sol_sub: "Sistemas prácticos de automatización con IA diseñados para flujos de trabajo empresariales reales — no simples demostraciones.",
    sol1_h: "Calificación de Leads con IA",
    sol1_p: "Puntúa, califica y distribuye leads automáticamente las 24 horas. Ningún lead caliente esperará mientras tu equipo está desconectado.",
    sol1_tag: "Automatización de Ventas",
    sol2_h: "Asistente de Soporte al Cliente con IA",
    sol2_p: "Implementa una IA que responde preguntas de clientes al instante, escala cuando es necesario y aprende de tu base de conocimiento.",
    sol2_tag: "Experiencia del Cliente",
    sol3_h: "Automatización de Seguimiento de Ventas con IA",
    sol3_p: "Secuencias de seguimiento automático activadas por comportamiento, etapa o tiempo — personalizadas por IA y enviadas en el momento adecuado.",
    sol3_tag: "Automatización de Ventas",
    sol4_h: "Programación de Citas con IA",
    sol4_p: "Deja que la IA gestione reservas, reprogramaciones y recordatorios de forma automática. Se integra con tu calendario y CRM.",
    sol4_tag: "Operaciones",
    sol5_h: "Automatización de CRM y Flujos de Trabajo con IA",
    sol5_p: "Automatiza la entrada de datos, actualizaciones del pipeline y creación de tareas en tu CRM. Mantén a tu equipo enfocado en cerrar ventas.",
    sol5_tag: "Operaciones",
    sol6_h: "Procesamiento de Documentos con IA",
    sol6_p: "Extrae, clasifica y procesa datos de contratos, formularios y facturas de forma automática — sin entrada manual.",
    sol6_tag: "Document AI",
    sol7_h: "Asistente de Conocimiento con IA",
    sol7_p: "Implementa un asistente de IA interno entrenado con el conocimiento de tu empresa — para tu equipo o tus clientes.",
    sol7_tag: "Knowledge AI",
    sol8_h: "Desarrollo Web con IA",
    sol8_p: "Diseñamos y construimos sitios web modernos y rápidos para tu negocio — optimizados para conversiones, mobile-first y listos para conectar con tu stack de automatización desde el primer día.",
    sol8_tag: "Desarrollo Web",
    sol9_h: "Visibilidad en Google y Búsqueda con IA",
    sol9_p: "Optimizamos tu presencia online para que tu negocio sea encontrado — en Google y dentro de asistentes de IA como ChatGPT, Claude, Gemini y Perplexity. El futuro de la búsqueda es con IA.",
    sol9_tag: "IA Search & SEO",
    sol_cta_h: "¿No sabes qué solución encaja mejor?",
    sol_cta_p: "Comenzamos cada proyecto con una Auditoría de Automatización con IA gratuita para identificar las oportunidades de mayor impacto en tu flujo de trabajo.",
    sol_cta_btn: "Obtén tu Auditoría Gratuita",

    // HOW IT WORKS
    how_label: "El Proceso",
    how_title: "De la auditoría a la automatización en vivo<br />en semanas, no en meses.",
    how_sub: "Un proceso claro y estructurado que entrega resultados con rapidez.",
    step1_h: "Auditoría de IA Gratuita",
    step1_p: "Analizamos tus flujos de trabajo actuales, identificamos cuellos de botella y trazamos exactamente dónde la automatización con IA aportará más valor — sin coste alguno.",
    step2_h: "Identificar Oportunidades",
    step2_p: "Priorizamos las oportunidades de automatización por ROI, construimos una hoja de ruta clara y acordamos los sistemas con mayor impacto para tu negocio.",
    step3_h: "Construir e Implementar",
    step3_p: "Desarrollamos los flujos de IA usando n8n, OpenAI, Claude AI y APIs modernas — probados, integrados y conectados a tus herramientas existentes.",
    step4_h: "Lanzar y Optimizar",
    step4_p: "Desplegamos tus sistemas de automatización, monitorizamos el rendimiento y optimizamos continuamente para que mejoren con el tiempo.",
    how_cta: "Comenzar con una Auditoría de IA Gratuita",

    // WHY
    why_label: "Por Qué Taskboost.ai",
    why_title: "IA Práctica.<br />Resultados Reales.",
    why_desc: "No vendemos hype de IA. Construimos sistemas de automatización que funcionan dentro de tus procesos empresariales reales, con herramientas modernas y entregando un impacto medible.",
    why_btn: "Reservar una Consulta Gratuita",
    why1_h: "Implementación Práctica ante Todo",
    why1_p: "Nos enfocamos en automatización que funciona en tu entorno real — no en pruebas de concepto que nunca llegan a producción.",
    why2_h: "Stack de IA Moderno",
    why2_p: "Usamos n8n, OpenAI, Claude AI, servicios de AWS AI y APIs modernas — las mismas herramientas que impulsan a los mejores equipos de automatización del mundo.",
    why3_h: "Experiencia Directa de los Fundadores",
    why3_p: "Trabajas directamente con los fundadores. Sin gestores de cuentas, sin traspasos a juniors — solo ingenieros experimentados que entienden tu negocio.",
    why4_h: "Capacidades Multilingües",
    why4_p: "Trabajamos con clientes y construimos sistemas de IA en inglés, alemán, español, portugués, rumano y catalán.",
    why5_h: "Certificado AWS Solutions Architect",
    why5_p: "Nuestro equipo posee la certificación AWS Solutions Architect — garantizando decisiones de arquitectura de nivel empresarial en cada proyecto.",
    why6_h: "Enfocados en Resultados Reales",
    why6_p: "Medimos el éxito por el tiempo ahorrado, los leads calificados y los costes reducidos — no por la complejidad de la tecnología utilizada.",

    // TOOLS
    tools_label: "Nuestro Stack Tecnológico",
    tools_title: "Construido con las mejores herramientas de IA disponibles",
    tools_sub: "Utilizamos las herramientas de IA y automatización más potentes y fiables para construir sistemas que funcionan — y siguen funcionando.",
    tool1_role: "Motor de Automatización de Flujos",
    tool1_desc: "Plataforma de automatización de código abierto que conecta todas tus aplicaciones, disparadores y agentes de IA en flujos de trabajo potentes de extremo a extremo.",
    tool1_badge: "Plataforma Principal",
    tool2_role: "GPT-4o · Embeddings · Assistants API",
    tool2_desc: "Impulsa nuestra IA conversacional, calificación de leads, asistentes de productos y flujos de procesamiento inteligente de documentos.",
    tool2_badge: "Modelos de IA",
    tool3_role: "Anthropic · Claude 3.5 Sonnet & Opus",
    tool3_desc: "Utilizado para razonamiento complejo, análisis de documentos con contexto extenso, asistentes de conocimiento e interacciones matizadas con clientes.",
    tool3_badge: "Modelos de IA",
    tool4_role: "Textract · Comprehend · Lambda · S3",
    tool4_desc: "Infraestructura cloud y servicios de IA de nivel empresarial para procesamiento de documentos, almacenamiento de datos y pipelines de automatización escalables.",
    tool4_badge: "Certificado AWS",
    tool5_role: "Integraciones Personalizadas · Triggers en Tiempo Real",
    tool5_desc: "Conectamos cualquier herramienta que tenga una API — CRMs, plataformas de e-commerce, calendarios, bases de datos y canales de comunicación.",
    tool5_badge: "Integración",
    tool6_role: "Pinecone · Supabase · Embeddings",
    tool6_desc: "Sistemas de recuperación de conocimiento que permiten a tus asistentes de IA responder preguntas desde tus propios datos, documentos y catálogo de productos.",
    tool6_badge: "Knowledge AI",

    // FOUNDERS
    found_label: "El Equipo",
    found_sub: "Taskboost.ai fue fundada en marzo de 2026 en Berlin, Germany, por un ingeniero y un filósofo con una convicción compartida: la automatización con IA debe ser práctica, rápida de desplegar y estar fundamentada en principios éticos que generen valor real para personas y empresas.",
    found1_role: "Co-Fundador y Tech Lead",
    found1_bio: "Especialista en tecnología con más de 10 años de experiencia en grandes empresas tecnológicas y startups en infraestructura cloud y desarrollo de software. Aporta una profunda experiencia en ingeniería de sistemas de IA, arquitectura de automatización e integraciones modernas de APIs.",
    found1_li: "Conectar en LinkedIn",
    found2_role: "Co-Fundador · IA Ética · Filosofía & IT",
    found2_bio: "Filósofo con formación en IT que garantiza que cada sistema que construimos esté fundamentado en principios éticos. Aporta una combinación única de conocimiento técnico y rigor filosófico — moldeando cómo Taskboost.ai concibe la responsabilidad de la IA, la transparencia y el impacto a largo plazo.",
    ethics_h: "Nuestro compromiso con la IA ética",
    ethics_p: "Creemos que la automatización con IA debe empoderar a las personas — no reemplazar su criterio, comprometer su privacidad ni crear sistemas que no comprenden. Cada automatización que construimos está diseñada para ser transparente, justa y genuinamente útil. La filosofía no es un interés secundario aquí — moldea cómo pensamos en cada sistema que construimos.",
    berlin_badge: "Fundada en marzo de 2026 · Berlin, Germany",

    // CONTACT
    contact_label: "Ponte en Contacto",
    contact_title: "Empieza con una<br />Auditoría de IA Gratuita.",
    contact_desc: "Cuéntanos sobre tu negocio e identificaremos las oportunidades de automatización con IA de mayor impacto — completamente gratis, sin compromiso.",
    contact_email_label: "Correo Electrónico",
    contact_wa_label: "WhatsApp",
    contact_loc_label: "Ubicación",
    contact_loc_val: "Berlin, Germany",
    contact_loc_sub: "Trabajamos con clientes en todo el mundo",
    contact_lang_label: "Hablamos",
    form_name: "Nombre Completo *",
    form_email: "Correo Empresarial *",
    form_company: "Empresa",
    form_phone: "Teléfono / WhatsApp",
    form_industry: "Sector",
    form_country: "País",
    form_other_industry: "Tu Sector",
    form_message: "Cuéntanos sobre tu flujo de trabajo *",
    ph_name: "Tu nombre completo",
    ph_email: "tu@empresa.com",
    ph_company: "Nombre de la empresa",
    ph_phone: "+1 234 567 8900",
    ph_country: "Tu país",
    ph_other_industry: "Ej: Salud, Logística, Finanzas...",
    ph_message: "Describe los procesos manuales que deseas automatizar o los retos a los que te enfrentas...",
    opt_select: "Selecciona un sector",
    opt_ecomm: "E-Commerce",
    opt_re: "Inmobiliaria",
    opt_other: "Otro",
    form_submit: "Obtener mi Auditoría de IA Gratuita",
    form_success_msg: "<strong>¡Mensaje enviado!</strong><p>Revisaremos tu flujo de trabajo y te responderemos en menos de 24 horas.</p>",

    // FOOTER
    footer_tagline: "Automatización práctica con IA para empresas de e-commerce e inmobiliarias. Construido en Berlin, sirviendo clientes globalmente.",
    footer_sol: "Soluciones",
    footer_sol1: "Calificación de Leads con IA",
    footer_sol2: "Soporte al Cliente con IA",
    footer_sol3: "Automatización de Seguimiento de Ventas",
    footer_sol4: "Programación de Citas",
    footer_sol5: "Automatización de CRM",
    footer_sol6: "Procesamiento de Documentos",
    footer_ind: "Sectores",
    footer_ind1: "E-Commerce",
    footer_ind2: "Inmobiliaria",
    footer_ind3: "Otros Sectores",
    footer_company: "Empresa",
    footer_comp1: "Nosotros",
    footer_comp2: "Fundadores",
    footer_comp3: "Cómo Funciona",
    footer_comp4: "Contacto",
    footer_contact: "Contacto",
    footer_copy: "&copy; 2026 Taskboost.ai · Todos los derechos reservados · Berlin, Germany",
  },

  /* ─────────────────────────────────────────────────────────────
     GERMAN (de)
  ───────────────────────────────────────────────────────────── */
  de: {
    // NAV
    nav_solutions: "Lösungen",
    nav_industries: "Branchen",
    nav_how: "So funktioniert es",
    nav_about: "Über uns",
    nav_reviews: "Bewertungen",
    nav_contact: "Kontakt",
    nav_cta: "Beratung buchen",
    rev_label: "Kundenbewertungen",
    rev_title: "Was unsere Kunden sagen",
    rev_sub: "Echte Ergebnisse von echten Unternehmen. Jede Bewertung wird geprüft und genehmigt, bevor sie hier erscheint.",
    rev_form_h: "Mit uns gearbeitet? Hinterlasse eine Bewertung",
    rev_form_sub: "Deine Bewertung wird vor der Veröffentlichung von unserem Team geprüft.",
    rev_pick_stars: "Bewertung auswählen",
    rev_name: "Dein Name *",
    rev_company: "Unternehmen (optional)",
    rev_role: "Deine Rolle (optional)",
    rev_text: "Deine Bewertung *",
    rev_submit: "Bewertung absenden",
    rev_note: "Vor der Veröffentlichung von unserem Team geprüft · Deine E-Mail wird nicht geteilt",
    rev_success: "Danke! Wir prüfen deine Bewertung und veröffentlichen sie bald.",

    // HERO
    hero_badge: "KI-Automatisierung",
    hero_title1: "Workflows automatisieren.",
    hero_title2: "Intelligenter skalieren.",
    hero_ethics: "KI-Ethik ist unser Kernwert — wir entwickeln Automatisierung, die transparent, fair und menschenzentriert ist.",
    hero_subtitle: "Taskboost.ai entwickelt praxisnahe KI-Automatisierungssysteme, die E-Commerce- und Immobilienunternehmen dabei helfen, manuelle Arbeit zu eliminieren, Abläufe zu optimieren und die Kundenkommunikation zu verbessern.",
    hero_cta1: "Kostenloses KI-Audit anfordern",
    hero_cta2: "So funktioniert es",
    hero_trust1: "AWS Solutions Architect Zertifiziert",
    card1_label: "Lead-Qualifizierung",
    card1_value: "247 Leads verarbeitet",
    card2_label: "KI-Support-Antwort",
    card2_value: "Antwort in &lt; 2 Sekunden",
    card3_label: "Eingesparte manuelle Aufgaben",
    card3_value: "~80% Reduktion",

    // VALUE
    val_label: "Warum KI-Automatisierung",
    val_title: "Dein Unternehmen sollte nicht von manueller Arbeit abhängen",
    val_sub: "Die meisten Unternehmen verlieren jeden Monat Hunderte von Stunden durch repetitive Aufgaben. Taskboost.ai ersetzt das durch KI-Systeme, die rund um die Uhr arbeiten.",
    val1_h: "Manuelle Arbeit eliminieren",
    val1_p: "Hör auf, dein Team für Copy-Paste-Aufgaben, Follow-up-E-Mails oder manuelle Lead-Qualifizierung zu bezahlen. Die KI erledigt die Routinearbeit automatisch.",
    val2_h: "Sofortige Kundenantworten",
    val2_p: "KI-Assistenten antworten Kunden binnen Sekunden — rund um die Uhr, in mehreren Sprachen — ohne zusätzliches Personal oder höhere Supportkosten.",
    val3_h: "Betrieb von Anfang bis Ende automatisieren",
    val3_p: "Von der Lead-Erfassung über den CRM-Eintrag bis zur Vertragsverarbeitung — wir bauen vernetzte KI-Pipelines, die komplette manuelle Workflows ersetzen.",
    val4_h: "Wachsen ohne neue Mitarbeiter",
    val4_p: "Steigere dein Volumen an Leads, Bestellungen oder Immobilienanfragen, ohne dein Team proportional zu vergrößern. KI skaliert mit dir.",

    // INDUSTRIES
    ind_label: "Unsere Zielbranchen",
    ind_title: "Entwickelt für E-Commerce.<br />Entwickelt für Immobilien.",
    ind_sub: "Tiefe Spezialisierung auf zwei Branchen, in denen KI-Automatisierung den größten Impact erzeugt.",
    ind1_tag: "Automatisierung für Onlineshops & Marktplätze",
    ind1_li1: "KI-gestützter Kundensupport-Assistent",
    ind1_li2: "Produktempfehlungs-Assistent",
    ind1_li3: "Automatisierte Bestellabwicklung",
    ind1_li4: "CRM- & Marketing-Automatisierung",
    ind1_li5: "KI-Assistent für Produktanfragen",
    ind1_li6: "Automatisierung von Retouren & Rückerstattungen",
    ind1_btn: "E-Commerce-Lösungen entdecken",
    ind2_tag: "Automatisierung für Agenturen & Immobilienteams",
    ind2_li1: "KI-gestütztes Lead-Qualifizierungssystem",
    ind2_li2: "Assistent für Immobilienanfragen",
    ind2_li3: "Automatisierte Terminplanung",
    ind2_li4: "CRM-Integration & Automatisierung",
    ind2_li5: "Mehrsprachige Kommunikationsautomatisierung",
    ind2_li6: "Dokumentenverarbeitung für Verträge",
    ind2_btn: "Immobilienlösungen entdecken",
    flex_h: "Deine Branche ist nicht dabei?",
    flex_p: "Auch wenn wir noch nicht in deiner Nische gearbeitet haben — unsere KI-Automatisierungs-Frameworks lassen sich an nahezu jeden Geschäftsprozess anpassen. Wir analysieren deine Abläufe, identifizieren Automatisierungspotenziale und entwickeln KI-Systeme, die auf dein Unternehmen zugeschnitten sind.",
    flex_btn: "Gespräch vereinbaren",

    // SHOWCASE
    show_label: "Echter Impact",
    show_title: "KI-Automatisierung in der Praxis",
    show_sub: "Von Onlineshops bis zu Immobilienagenturen — Teams, die automatisieren, skalieren schneller, reagieren zügiger und schließen mehr Abschlüsse.",
    show1_tag: "E-Commerce",
    show1_h: "Kundensupport automatisiert.<br />Das Team kann endlich wachsen.",
    show1_p: "Die KI beantwortet Produktfragen, bearbeitet Retouren und qualifiziert Käufer — ohne eine einzige manuelle Berührung.",
    show2_tag: "Immobilien",
    show2_h: "Jeder Lead automatisch qualifiziert.",
    show2_p: "Die KI führt Erstgespräche, vereinbart Besichtigungen und aktualisiert das CRM — damit Makler nur noch mit ernsthaften Käufern sprechen.",
    show3_tag: "Betrieb",
    show3_h: "80% weniger manuelle Arbeit. Dasselbe Team.",
    show3_p: "Automatisierte Workflows ersetzen repetitive Aufgaben, damit dein Team seine Zeit für das investiert, was das Geschäft wirklich voranbringt.",
    stat1_label: "Reduktion manueller Aufgaben",
    stat2_label: "KI-Reaktionszeit im Kundensupport",
    stat3_label: "Automatisierte Betriebsabläufe",
    stat4_label: "Vom Audit zur Live-Automatisierung",

    // SOLUTIONS
    sol_label: "KI-Lösungen",
    sol_title: "Was wir für dich bauen",
    sol_sub: "Praxisnahe KI-Automatisierungssysteme für echte Geschäftsprozesse — keine reinen Demo-Projekte.",
    sol1_h: "KI-Lead-Qualifizierung",
    sol1_p: "Leads automatisch bewerten, qualifizieren und weiterleiten — 24/7. Kein heißer Lead wartet mehr, während dein Team offline ist.",
    sol1_tag: "Vertriebsautomatisierung",
    sol2_h: "KI-Kundensupport-Assistent",
    sol2_p: "Setze eine KI ein, die Kundenfragen sofort beantwortet, bei Bedarf eskaliert und aus deiner Wissensdatenbank lernt.",
    sol2_tag: "Kundenerlebnis",
    sol3_h: "KI-gestützte Vertriebsnachverfolgung",
    sol3_p: "Automatische Follow-up-Sequenzen, ausgelöst durch Verhalten, Phase oder Zeit — von der KI personalisiert, zum richtigen Zeitpunkt versendet.",
    sol3_tag: "Vertriebsautomatisierung",
    sol4_h: "KI-Terminplanung",
    sol4_p: "Lass die KI Buchungen, Umbuchungen und Erinnerungen automatisch verwalten. Nahtlose Integration mit deinem Kalender und CRM.",
    sol4_tag: "Betrieb",
    sol5_h: "KI-CRM & Workflow-Automatisierung",
    sol5_p: "Dateneingabe, Pipeline-Updates und Aufgabenerstellung im CRM vollständig automatisieren. Dein Team bleibt auf Abschlüsse fokussiert.",
    sol5_tag: "Betrieb",
    sol6_h: "KI-Dokumentenverarbeitung",
    sol6_p: "Daten aus Verträgen, Formularen und Rechnungen automatisch extrahieren, klassifizieren und verarbeiten — ohne manuelle Eingabe.",
    sol6_tag: "Document AI",
    sol7_h: "KI-Wissensassistent",
    sol7_p: "Setze einen internen KI-Assistenten ein, der mit dem Wissen deines Unternehmens trainiert wurde — für dein Team oder deine Kunden.",
    sol7_tag: "Knowledge AI",
    sol8_h: "KI-gestützte Website-Entwicklung",
    sol8_p: "Wir entwerfen und bauen schnelle, moderne Websites für dein Unternehmen — konversionsoptimiert, mobile-first und von Anfang an bereit für die Verbindung mit deinem KI-Automatisierungs-Stack.",
    sol8_tag: "Webentwicklung",
    sol9_h: "Sichtbarkeit auf Google & KI-Suche",
    sol9_p: "Wir optimieren deine Online-Präsenz, damit dein Unternehmen gefunden wird — auf Google und in KI-Assistenten wie ChatGPT, Claude, Gemini und Perplexity. Die Zukunft der Suche ist KI-gesteuert.",
    sol9_tag: "KI-Suche & SEO",
    sol_cta_h: "Nicht sicher, welche Lösung passt?",
    sol_cta_p: "Jedes Projekt beginnen wir mit einem kostenlosen KI-Automatisierungs-Audit, um die chancenreichsten Bereiche in deinem spezifischen Workflow zu identifizieren.",
    sol_cta_btn: "Kostenloses Audit anfordern",

    // HOW IT WORKS
    how_label: "Der Prozess",
    how_title: "Vom Audit zur Live-Automatisierung<br />in Wochen, nicht Monaten.",
    how_sub: "Ein klarer, strukturierter Prozess, der schnell Ergebnisse liefert.",
    step1_h: "Kostenloses KI-Audit",
    step1_p: "Wir analysieren deine aktuellen Workflows, identifizieren Engpässe und zeigen genau auf, wo KI-Automatisierung den größten Mehrwert bringt — kostenlos.",
    step2_h: "Potenziale identifizieren",
    step2_p: "Wir priorisieren Automatisierungsmöglichkeiten nach ROI, erstellen eine klare Roadmap und einigen uns auf die Systeme mit dem größten Impact für dein Unternehmen.",
    step3_h: "Aufbauen & Implementieren",
    step3_p: "Wir entwickeln die KI-Workflows mit n8n, OpenAI, Claude AI und modernen APIs — getestet, integriert und mit deinen bestehenden Tools verbunden.",
    step4_h: "Launchen & Optimieren",
    step4_p: "Wir deployen deine Automatisierungssysteme, überwachen die Performance und optimieren kontinuierlich, damit sie sich im Laufe der Zeit verbessern.",
    how_cta: "Mit einem kostenlosen KI-Audit starten",

    // WHY
    why_label: "Warum Taskboost.ai",
    why_title: "Praxisnahe KI.<br />Echte Ergebnisse.",
    why_desc: "Wir verkaufen keinen KI-Hype. Wir bauen Automatisierungssysteme, die in deinen realen Geschäftsprozessen funktionieren, moderne Tools nutzen und messbaren Impact liefern.",
    why_btn: "Kostenlose Beratung buchen",
    why1_h: "Praxisorientierte Umsetzung an erster Stelle",
    why1_p: "Wir konzentrieren uns auf Automatisierung, die in deiner echten Umgebung läuft — keine Machbarkeitsstudien, die nie in Produktion gehen.",
    why2_h: "Moderner KI-Stack",
    why2_p: "Wir setzen n8n, OpenAI, Claude AI, AWS KI-Services und moderne APIs ein — dieselben Werkzeuge, mit denen die besten Automatisierungsteams der Welt arbeiten.",
    why3_h: "Direkte Expertise der Gründer",
    why3_p: "Du arbeitest direkt mit den Gründern. Keine Account-Manager, keine Übergaben an Junior-Mitarbeiter — nur erfahrene Ingenieure, die dein Geschäft verstehen.",
    why4_h: "Mehrsprachige Kompetenz",
    why4_p: "Wir arbeiten mit Kunden und entwickeln KI-Systeme auf Englisch, Deutsch, Spanisch, Portugiesisch, Rumänisch und Katalanisch.",
    why5_h: "AWS Solutions Architect Zertifiziert",
    why5_p: "Unser Team ist AWS Solutions Architect zertifiziert — das garantiert architektonische Entscheidungen auf Enterprise-Niveau für jedes Projekt.",
    why6_h: "Fokus auf echte Ergebnisse",
    why6_p: "Wir messen Erfolg an eingesparter Zeit, qualifizierten Leads und reduzierten Kosten — nicht an der Komplexität der eingesetzten Technologie.",

    // TOOLS
    tools_label: "Unser Tech-Stack",
    tools_title: "Gebaut mit den besten verfügbaren KI-Tools",
    tools_sub: "Wir nutzen die leistungsstärksten und zuverlässigsten KI- und Automatisierungstools, um Systeme zu bauen, die funktionieren — und es bleiben.",
    tool1_role: "Workflow-Automatisierungsplattform",
    tool1_desc: "Open-Source-Automatisierungsplattform, die alle deine Apps, Trigger und KI-Agenten zu leistungsstarken End-to-End-Workflows verbindet.",
    tool1_badge: "Kernplattform",
    tool2_role: "GPT-4o · Embeddings · Assistants API",
    tool2_desc: "Treibt unsere konversationelle KI, Lead-Qualifizierung, Produktassistenten und intelligente Dokumentenverarbeitungs-Workflows an.",
    tool2_badge: "KI-Modelle",
    tool3_role: "Anthropic · Claude 3.5 Sonnet & Opus",
    tool3_desc: "Für komplexes Reasoning, Dokumentenanalyse mit langem Kontext, Wissensassistenten und differenzierte Kundeninteraktionen eingesetzt.",
    tool3_badge: "KI-Modelle",
    tool4_role: "Textract · Comprehend · Lambda · S3",
    tool4_desc: "Cloud-Infrastruktur und KI-Services auf Enterprise-Niveau für Dokumentenverarbeitung, Datenspeicherung und skalierbare Automatisierungs-Pipelines.",
    tool4_badge: "AWS Zertifiziert",
    tool5_role: "Custom Integrationen · Echtzeit-Trigger",
    tool5_desc: "Wir verbinden jedes Tool mit einer API — CRMs, E-Commerce-Plattformen, Kalender, Datenbanken und Kommunikationskanäle.",
    tool5_badge: "Integration",
    tool6_role: "Pinecone · Supabase · Embeddings",
    tool6_desc: "Wissensabruf-Systeme, die deinen KI-Assistenten ermöglichen, Fragen aus deinen eigenen Daten, Dokumenten und Produktkatalog zu beantworten.",
    tool6_badge: "Knowledge AI",

    // FOUNDERS
    found_label: "Das Team",
    found_sub: "Taskboost.ai wurde im März 2026 in Berlin, Germany, von einem Ingenieur und einem Philosophen gegründet, die eine gemeinsame Überzeugung teilen: KI-Automatisierung sollte praxisnah, schnell einsetzbar und auf ethischen Grundlagen gebaut sein, die echten Mehrwert für Menschen und Unternehmen schaffen.",
    found1_role: "Co-Gründer & Tech Lead",
    found1_bio: "Technologiespezialist mit über 10 Jahren Erfahrung bei großen Technologieunternehmen und Startups in den Bereichen Cloud-Infrastruktur und Softwareentwicklung. Bringt tiefe Engineering-Expertise in KI-Systemen, Automatisierungsarchitektur und modernen API-Integrationen in jedes Projekt ein.",
    found1_li: "Auf LinkedIn verbinden",
    found2_role: "Co-Gründer · KI-Ethik · Philosophie & IT",
    found2_bio: "Philosoph mit IT-Hintergrund, der sicherstellt, dass jedes System, das wir bauen, auf ethischen Grundsätzen beruht. Bringt eine seltene Kombination aus technischem Wissen und philosophischer Strenge mit — und prägt, wie Taskboost.ai über KI-Verantwortung, Transparenz und langfristige Auswirkungen denkt.",
    ethics_h: "Unser Engagement für ethische KI",
    ethics_p: "Wir glauben, dass KI-Automatisierung Menschen stärken sollte — nicht ihr Urteilsvermögen ersetzen, ihre Privatsphäre gefährden oder Systeme schaffen, die sie nicht verstehen. Jede Automatisierung, die wir entwickeln, ist darauf ausgelegt, transparent, fair und genuinely nützlich zu sein. Philosophie ist hier kein Nebenhobby — sie prägt, wie wir über jedes System nachdenken, das wir bauen.",
    berlin_badge: "Gegründet im März 2026 · Berlin, Germany",

    // CONTACT
    contact_label: "Kontakt aufnehmen",
    contact_title: "Starte mit einem<br />kostenlosen KI-Audit.",
    contact_desc: "Erzähl uns von deinem Unternehmen und wir identifizieren die wirkungsvollsten KI-Automatisierungsmöglichkeiten — völlig kostenlos, ohne Verpflichtung.",
    contact_email_label: "E-Mail",
    contact_wa_label: "WhatsApp",
    contact_loc_label: "Standort",
    contact_loc_val: "Berlin, Germany",
    contact_loc_sub: "Wir arbeiten mit Kunden weltweit",
    contact_lang_label: "Wir sprechen",
    form_name: "Vollständiger Name *",
    form_email: "Geschäftliche E-Mail *",
    form_company: "Unternehmen",
    form_phone: "Telefon / WhatsApp",
    form_industry: "Branche",
    form_country: "Land",
    form_other_industry: "Deine Branche",
    form_message: "Erzähl uns von deinen Workflows *",
    ph_name: "Dein vollständiger Name",
    ph_email: "du@unternehmen.com",
    ph_company: "Unternehmensname",
    ph_phone: "+49 123 456 789",
    ph_country: "Dein Land",
    ph_other_industry: "z. B. Gesundheit, Logistik, Finanzen...",
    ph_message: "Beschreibe die manuellen Prozesse, die du automatisieren möchtest, oder die Herausforderungen, vor denen du stehst...",
    opt_select: "Branche auswählen",
    opt_ecomm: "E-Commerce",
    opt_re: "Immobilien",
    opt_other: "Sonstiges",
    form_submit: "Kostenloses KI-Audit anfordern",
    form_success_msg: "<strong>Nachricht gesendet!</strong><p>Wir werden deinen Workflow prüfen und uns innerhalb von 24 Stunden bei dir melden.</p>",

    // FOOTER
    footer_tagline: "Praxisnahe KI-Automatisierung für E-Commerce- und Immobilienunternehmen. Entwickelt in Berlin, für Kunden weltweit.",
    footer_sol: "Lösungen",
    footer_sol1: "KI-Lead-Qualifizierung",
    footer_sol2: "KI-Kundensupport",
    footer_sol3: "Vertriebsnachverfolgung automatisieren",
    footer_sol4: "Terminplanung",
    footer_sol5: "CRM-Automatisierung",
    footer_sol6: "Dokumentenverarbeitung",
    footer_ind: "Branchen",
    footer_ind1: "E-Commerce",
    footer_ind2: "Immobilien",
    footer_ind3: "Weitere Branchen",
    footer_company: "Unternehmen",
    footer_comp1: "Über uns",
    footer_comp2: "Gründer",
    footer_comp3: "So funktioniert es",
    footer_comp4: "Kontakt",
    footer_contact: "Kontakt",
    footer_copy: "&copy; 2026 Taskboost.ai · Alle Rechte vorbehalten · Berlin, Germany",
  },

};

/* ─────────────────────────────────────────────────────────────
   APPLY LANGUAGE
───────────────────────────────────────────────────────────── */
function applyLang(lang) {
  const t = translations[lang];
  if (!t) return;

  // Translate all data-i18n elements
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });

  // Translate placeholders
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    if (t[key] !== undefined) el.placeholder = t[key];
  });

  // Update active button state
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });

  // Update html lang attribute
  document.documentElement.lang = lang;

  // Persist preference
  localStorage.setItem('tb_lang', lang);
}

/* ─────────────────────────────────────────────────────────────
   INIT
───────────────────────────────────────────────────────────── */
document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('tb_lang');
  const browser = navigator.language.slice(0, 2).toLowerCase();
  const detected = ['es', 'de'].includes(browser) ? browser : 'en';
  const lang = saved || detected;

  applyLang(lang);

  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => applyLang(btn.dataset.lang));
  });
});
